LOADING_MESSAGES = [
    "Cooking…",
    "Hatching…",
    "Holding tight…",
    "Thinking deeply…",
    "Assembling words…",
    "Mining knowledge…",
    "Warming up neurons…",
    "Igniting neurons…",
    "Fetching wisdom…",
    "Organizing thoughts…",
    "Brewing a reply…",
    "Whispering to the void…",
    "Waking up circuits…",
    "Summoning data spirits…",
    "Searching the ether…",
    "Pondering the imponderable…",
    "Conjuring thoughts…",
    "Scribbling on a digital napkin…",
    "Zipping up bits and bytes…",
]
