# Default model (gpt-3.5-turbo, gpt-4, ggml-gpt4all-j...)
default-model: google-gla:gemini-2-flash
# List of predefined system messages that can be used as roles
roles:
  "default": []
  # Example, a role called `shell`:
  shell:
    - you are a shell expert
    - you do not explain anything
    - you simply output one liners to solve the problems you're asked
    - you do not provide any explanation whatsoever, ONLY the command
# System role to use
role: "default"
